### PR TITLE
Use core::mem::align_of to determine proper type aligment

### LINKED ISSUE #56: "cargo test --features=serde" fails on i686
```
failures:
 
 ---- tests::test_data_ptr_alignment stdout ----
 thread 'tests::test_data_ptr_alignment' panicked at 'assertion failed: v.data_raw() as usize % 8 == 0', src/lib.rs:2666:9
```

### PR DESCRIPTION
**Pull request by jamessan**
On i686, the u64 test sometimes fails because the required alignment is
4-bytes, not 8-bytes.

Closes #56
Co-authored-by: Peter Michael Green <plugwash@debian.org>

### CODE REVIEW

File: src/lib.rs [hunk 1]
```diff
@@ -2657,13 +2657,13 @@ mod tests {
     #[test]
     fn test_data_ptr_alignment() {
         let v = ThinVec::<u16>::new();
-        assert!(v.data_raw() as usize % 2 == 0);
+        assert!(v.data_raw() as usize % core::mem::align_of::<u16>() == 0);
```
Comment (workingjubilee) [inline src/lib.rs:2660]: This is prelude now:
```suggestion
        assert!(v.data_raw() as usize % align_of::<u16>() == 0);
```

File: src/lib.rs [hunk 2]
```diff
@@ -2657,13 +2657,13 @@ mod tests {
...
 
         let v = ThinVec::<u32>::new();
-        assert!(v.data_raw() as usize % 4 == 0);
+        assert!(v.data_raw() as usize % core::mem::align_of::<u32>() == 0);
```
Comment (workingjubilee) [inline src/lib.rs:2663]:
```suggestion
        assert!(v.data_raw() as usize % align_of::<u32>() == 0);
```

File: src/lib.rs [hunk 3]
```diff
@@ -2657,13 +2657,13 @@ mod tests {
...
 
         let v = ThinVec::<u64>::new();
-        assert!(v.data_raw() as usize % 8 == 0);
+        assert!(v.data_raw() as usize % core::mem::align_of::<u64>() == 0);
```
Comment (workingjubilee) [inline src/lib.rs:2666]:
```suggestion
        assert!(v.data_raw() as usize % align_of::<u64>() == 0);
```

**Comment by jamessan** [comment]
They were only added to the prelude in [1.80](https://doc.rust-lang.org/stable/releases.html#version-1800-2024-07-25). Since this project doesn't declare what its minimum rust version is, I don't see why I should rely on align_of being part of the prelude.

**Review by hkBst — APPROVED** [review]
